openapi: 3.1.0
info:
  title: Arthur GenAI Engine Agent Discovery Secrets API
  version: 2.1.688
  description: Endpoints for secrets management
tags:
- name: Secrets
  description: Endpoints for secrets management
paths:
  /api/v1/secrets/rotation:
    post:
      tags:
      - Secrets
      summary: Rotates secrets
      description: "This endpoint re-encrypts all the secrets in the database. The procedure calling this endpoint is as follows: \nFirst: Deploy a new version of the service with GENAI_ENGINE_SECRET_STORE_KEY set to a value like 'new-key::old-key'. \nSecond: call this endpoint - all secrets will be re-encrypted with 'new-key'. \nThird: Deploy a new version of the service removing the old key from GENAI_ENGINE_SECRET_STORE_KEY, like 'new-key'. \nAt this point all existing and new secrets will be managed by 'new-key'."
      operationId: rotate_secrets_api_v1_secrets_rotation_post
      responses:
        '204':
          description: Secrets rotated.
      security:
      - API Key: []
components:
  securitySchemes:
    API Key:
      type: http
      description: Bearer token authentication with an API key
      scheme: bearer
